### ISSUE TITLE
Uncaught TypeError: Accessing selectionEnd on an input element that cannot have a selection.

### ISSUE THREAD

**Issue by danbramall** [AliasIO/Raphael.JSON#1]
Hi,

This has all been working great for me in Firefox 8, but I've just tried in Chrome 15 and I get this console error when executing: 

```
paper.to_json();
```

The error in the console is:

Uncaught TypeError: Accessing selectionEnd on an input element that cannot have a selection.
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
derez cycle.js:79
decycle cycle.js:90
Raphael.fn.to_json raphael-json.js:18
(anonymous function) my-peripherals.js:157
f.event.dispatch jquery.min.js:3
f.event.add.h.handle.i jquery.min.js:3

Any ideas Elbert?

Thanks

**Comment by AliasIO** [comment]
I'm getting a different error in Chrome:

```
Uncaught RangeError: Maximum call stack size exceeded
```

It looks like the object is too large, or cycle.js isn't properly derezzing the object (I suspect the former). I may need to change the script a bit to only export the essential bits.

**Comment by danbramall** [comment]
Ah, that's interesting, thanks Elbert.  Do you have an ETA for a fix on this?  Not hassling, just curious as I have a project which uses this right now and need to feed back to the client.  My scripting skills probably aren't up to fixing this personally, but I might be able to donate to the project if that helps?  Happy to do what I can, as it's a useful bit of code and I appreciate what you're doing here.

**Comment by AliasIO** [comment]
You may be able to work with my fork of the original project:

https://github.com/ElbertF/raphael.serialize

I have a lot going on but will see what I can do. Hopefully I'll get around to it this week.

**Comment by AliasIO** [comment]
An hour later... This should now be fixed. I removed recursion and the dependency on cycle.js by only serializing what's needed to rebuild the elements.

https://github.com/ElbertF/Raphael.JSON/blob/master/raphael.json.js

**Comment by danbramall** [comment]
Awesome! That works brilliantly, thanks Elbert - I really appreciate this!
