### ISSUE TITLE
JSON is Undefined in ie6 and 7

### ISSUE THREAD

**Issue by mrpickles3rd** [AliasIO/Raphael.JSON#11]
Hi,  sorry if this has been covered already but I am trying to get 'toJSON()' working in IE6 and 7 but get the below error in the console of ie9 -> document mode: IE7 standards

Error:
SCRIPT5009: 'JSON' is undefined 
raphael.serialize.js, line 26 character 3

I have Jquery .1.7.2,  Raphiael 2.1  and your latest code all linking in that order at the very end of my javascript files

do you have a fix?

**Comment by AliasIO** [comment]
IE6 and 7 don't support JSON natively so you'll need to include [json.js](https://github.com/douglascrockford/JSON-js/blob/master/json.js).

**Comment by mrpickles3rd** [comment]
thank you!
