### ISSUE TITLE
Raphael.JSON callback saving wrong values for transformation attribute

### ISSUE THREAD

**Issue by shirkavand** [AliasIO/Raphael.JSON#13]
Hi ElbertF,

I am using Raphael.JSON callback in order to create a JSON representation of Raphael's different objects. The problem is that when i debug the final generated JSON created by the callback function the "transform" attribute does not match the values that are currently stored in the HTML, for example: after rotating, resizing etc an image, using firebug the "transform" attribute of the image in the HTML is:

transform="matrix(-1.6092,0.0554,-0.0554,-1.6092,1318.5385,773.6154)"

But in the generated JSON the value is:

"transform":"t1318.5384615014195,773.6153848834983s1.6102,1.6102,0,0r178.0288,0,0"

If i use the values that are stored in the JSON object for creating a SVG file(for example), the SVG file does not has any of the transformations made by the user, in the other hand, if i use the values  that the HTML has the SVG file is generated properly(with all the transformations made by the user).

I checked Raphael.JSON pluggin, maybe this line needs to be chaged?:

transform: el.matrix.toTransformString()

Any idea/tip why is this happening?

Warm Regards,

Shirkavnd

**Comment by shirkavand** [comment]
Never mind. I used your great export pluggin https://github.com/ElbertF/Raphael.Export

you rock!

**Comment by AliasIO** [comment]
The SVG attribute looks slightly different from Raphael's transformation string, you need to manually convert it. Raphael.JSON simply stores whatever it needs to restore the previous state.
