### ISSUE TITLE
ReferenceError: json is not defined

### ISSUE THREAD

**Issue by dazza100** [AliasIO/Raphael.JSON#16]
HI

I've setup a simple sample page. The Json object is created but when i try and load it back i get

ReferenceError: json is not defined

paper.fromJSON(json);

http://www.lazynails.com/svg/demo.html

Can you help

Thank you 

Dazza

**Comment by AliasIO** [comment]
If you use `var` inside a function that variable will only be available in the scope of that function. If you define it outside the function it will work:

``` javascript
$('#clickhere').click(function() {
    var json = paper.toJSON();
```

``` javascript
var json;

$('#clickhere').click(function() {
    json = paper.toJSON();
```

**Comment by dazza100** [comment]
Hi Elbert

Thank you!

Darren

On 12 Jan 2013, at 00:14, Elbert Alias wrote:

If you use var inside a function that variable will only be available in the scope of that function. If you define it outside the function it will work:

$('#clickhere').click(function() {
    var json = paper.toJSON();
var json;

$('#clickhere').click(function() {
    json = paper.toJSON();

**Comment by dazza100** [comment]
Hi Elbert

I hope you are well. I'm trying to save and reload the canvas. It seems to be working well apart from when i scale text or images. They are positioned in the correct place but when i click on them the free transform handles are not in the correct position. Is there an easy way to fix this?

The checkout button will save canvas then reload it. 
http://www.lazynails.com/index.php?route=nail/designer 

Thanks again

Dazza

**Comment by AliasIO** [comment]
It sounds similar to this issue:

https://github.com/ElbertF/Raphael.FreeTransform/issues/76

Are you using Raphael methods to apply transformations? If so, try using FreeTransform methods instead.

Feel free to open a new issue if you have questions.

**Comment by dazza100** [comment]
HI Elbert

Thanks for getting back to me. I think this problem is slightly different. 
I'm using free transform. It works perfectly. 
I'm trying to save the canvas to database then reload it. The text is in the correct position but the handles and bounding box are not in the correct place. This only happens on text and images that have been scaled or rotated prior to saving. If i move the handles the text will reposition inside the bounding box and continues to work as expected. 

Thanks again

Dazza
