### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jberryman** [AliasIO/Raphael.JSON#2]
- README should be updated to reflect that project no longer depends on cycle.js.
- A little note that this project is based on / inspired by https://github.com/jspies/raphael.serialize and a little information on the difference would be helpful. E.g. the code by jspies has a separate case for each of several shape elements, but Raphael.JSON seems to serialize everything and is much smaller. Are there tradeoffs or does Raphael.JSON work just as well?

Thanks for your work on this project!

**Comment by AliasIO** [comment]
Thanks, I'll update the README.

As far as I know there are no tradeoffs, it's just a more efficient way of doing the same thing. Jonathan's version was built for an older version of Raphael, it may have been different then.
