### ISSUE TITLE
json[i].node is undefined

### ISSUE THREAD

**Issue by danbramall** [AliasIO/Raphael.JSON#6]
Hi,

I've just updated to the latest version of this plug-in to see if it works in <ie9 (the old version I have didn't work in <ie9).  However whenever the script is loaded at all it errors:

json[i].node is undefined

line 40:  element.node.id = json[i].node.id;

The only thing I've changed is the function names to maintain legacy calls to the old version (named back to to_json and from_json which is what they were called originally).

Do you know why this is erroring or how to fix?

Thanks!

**Comment by AliasIO** [comment]
Are you importing JSON that was exported using the old version? I recently made to export the element's id.

You can fix line 40 by adding a check:

```
element.node.id = json[i].node.id; // Change this...
element.node.id = typeof json[i].node !== 'undefined' ? json[i].node.id : ''; // ...to this.
```
