### ISSUE TITLE
draggable elements not draggable anymore after save/load

### ISSUE THREAD

**Issue by oscargala** [AliasIO/Raphael.JSON#9]
Hi,

I am trying to make a Raphael diagram editor where I can save / load the diagrams. I am using your Json code for the saving and loading.  

It saves and loads all the elements, but after I load them in again, their draggable functionality is gone. Any idea how I can restore that functionality after loading a previously saved version?
Any help would be greatly appreciated.

Edit:  It looks like the data attributes of elements and onClick events are not saved as well.  Any idea on how to save those?

**Comment by AliasIO** [comment]
Hi,

There is no way to serialize functions so you need to rebind events after loading the elements. I'm planning on adding a callback function that should make this a little easier, see my comment here:

https://github.com/ElbertF/Raphael.JSON/pull/8#issuecomment-4045548

With this you'll also be able to save other attributes such as `data`. It's currently not possible for the plugin to get all saved `data` values, see my pull request here:

https://github.com/DmitryBaranovskiy/raphael/pull/510

I'm closing this issue but feel free to keep this conversation going.

**Comment by AliasIO** [comment]
Callback functions have been added in 27feebc62a3a05835c9f6f6db9837d24b7052a01.

**Comment by oscargala** [comment]
Thanks for the quick update!  I had actually managed to keep the data and keep the elements drag-able after a save/load by altering the code myself. 

I am making sets of a path with a text element and making them both draggable by creating pairs as discussed here: http://stackoverflow.com/questions/3679436/how-can-i-combine-objects-in-the-raphael-javascript-library

My raphael.json code is here: http://hastebin.com/yemayaxoma.js

**Comment by AliasIO** [comment]
It looks like you should be able to port your code to the updated Raphael.JSON. With the callbacks there's no need to modify the plugin.

**Comment by oscargala** [comment]
I agree. Will try that this weekend.
